### ISSUE TITLE
在群内发送sudo tps引发报错

### ISSUE THREAD

**Issue by zzj2039** [mcdoeswhat/AmazingBot-4#7]
`[17:20:21] [Craft Scheduler Thread - 24/WARN]: me.albert.amazingbot.shaded.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.message
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.shaded.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:225)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.shaded.gson.Gson.fromJson(Gson.java:991)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.shaded.gson.Gson.fromJson(Gson.java:1062)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.shaded.gson.Gson.fromJson(Gson.java:1034)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.bot.BotEventParser.parse(BotEventParser.java:48)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.bot.BotEventParser.parseMessageEvent(BotEventParser.java:110)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.bot.BotEventParser.parseEvent(BotEventParser.java:38)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.bot.BotClient.processMessageRec(BotClient.java:131)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.bot.BotClient.lambda$onMessage$0(BotClient.java:108)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: Caused by: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.message
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.shaded.gson.internal.bind.JsonTreeReader.nextString(JsonTreeReader.java:181)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.shaded.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:393)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.shaded.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:381)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.shaded.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	at me.albert.amazingbot.shaded.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
[17:20:21] [Craft Scheduler Thread - 24/WARN]: 	... 14 more`

**Comment by RushCN** [comment]
请问是怎么解决的？我也有这问题
